!     -*- f90 -*-
!     This file is autogenerated with f2py (version:1.24.3)
!     It contains Fortran 90 wrappers to fortran functions.

      
      subroutine f2pyinitspecpart(f2pysetupfunc)
      use specpart, only : ihmax
      use specpart, only : npart
      use specpart, only : partinit
      use specpart, only : partition
      use specpart, only : ptsort
      use specpart, only : ptnghb
      use specpart, only : pt_fld
      external f2pysetupfunc
      call f2pysetupfunc(ihmax,npart,partinit,partition,ptsort,ptnghb,pt&
     &_fld)
      end subroutine f2pyinitspecpart


