/* File: specpartmodule.c
 * This file is auto-generated with f2py (version:1.24.3).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Thu Mar  7 07:24:40 2024
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef PY_SSIZE_T_CLEAN
#define PY_SSIZE_T_CLEAN
#endif /* PY_SSIZE_T_CLEAN */

/* Unconditionally included */
#include <Python.h>
#include <numpy/npy_os.h>

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *specpart_error;
static PyObject *specpart_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

/* See fortranobject.h for definitions. The macros here are provided for BC. */
#define rank f2py_rank
#define shape f2py_shape
#define fshape f2py_shape
#define len f2py_len
#define flen f2py_flen
#define slen f2py_slen
#define size f2py_size

#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(specpart_error,errstring);\
        /*goto capi_fail;*/\
    } else 
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int
int_from_pyobj(int* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;

    if (PyLong_Check(obj)) {
        *v = Npy__PyLong_AsInt(obj);
        return !(*v == -1 && PyErr_Occurred());
    }

    tmp = PyNumber_Long(obj);
    if (tmp) {
        *v = Npy__PyLong_AsInt(tmp);
        Py_DECREF(tmp);
        return !(*v == -1 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (int_from_pyobj(v, tmp, errmess)) {
            Py_DECREF(tmp);
            return 1;
        }
        Py_DECREF(tmp);
    }

    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = specpart_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/********************************** partinit **********************************/
static char doc_f2py_rout_specpart_specpart_partinit[] = "\
partinit(nk,nth)\n\nWrapper for ``partinit``.\
\n\nParameters\n----------\n"
"nk : input int\n"
"nth : input int";
/*  */
static PyObject *f2py_rout_specpart_specpart_partinit(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int nk = 0;
    PyObject *nk_capi = Py_None;
    int nth = 0;
    PyObject *nth_capi = Py_None;
    static char *capi_kwlist[] = {"nk","nth",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OO|:specpart.specpart.partinit",\
        capi_kwlist,&nk_capi,&nth_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable nk */
        f2py_success = int_from_pyobj(&nk,nk_capi,"specpart.specpart.partinit() 1st argument (nk) can't be converted to int");
    if (f2py_success) {
    /* Processing variable nth */
        f2py_success = int_from_pyobj(&nth,nth_capi,"specpart.specpart.partinit() 2nd argument (nth) can't be converted to int");
    if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&nk,&nth);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*if (f2py_success) of nth*/
    /* End of cleaning variable nth */
    } /*if (f2py_success) of nk*/
    /* End of cleaning variable nk */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/****************************** end of partinit ******************************/

/********************************* partition *********************************/
static char doc_f2py_rout_specpart_specpart_partition[] = "\
ipart = partition(spec,[nk,nth])\n\nWrapper for ``partition``.\
\n\nParameters\n----------\n"
"spec : input rank-2 array('f') with bounds (nk,nth)\n"
"\nOther Parameters\n----------------\n"
"nk : input int, optional\n    Default: shape(spec, 0)\n"
"nth : input int, optional\n    Default: shape(spec, 1)\n"
"\nReturns\n-------\n"
"ipart : rank-2 array('i') with bounds (nk,nth)";
/*  */
static PyObject *f2py_rout_specpart_specpart_partition(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,int*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    float *spec = NULL;
    npy_intp spec_Dims[2] = {-1, -1};
    const int spec_Rank = 2;
    PyArrayObject *capi_spec_as_array = NULL;
    int capi_spec_intent = 0;
    PyObject *spec_capi = Py_None;
    int *ipart = NULL;
    npy_intp ipart_Dims[2] = {-1, -1};
    const int ipart_Rank = 2;
    PyArrayObject *capi_ipart_as_array = NULL;
    int capi_ipart_intent = 0;
    int nk = 0;
    PyObject *nk_capi = Py_None;
    int nth = 0;
    PyObject *nth_capi = Py_None;
    static char *capi_kwlist[] = {"spec","nk","nth",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|OO:specpart.specpart.partition",\
        capi_kwlist,&spec_capi,&nk_capi,&nth_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable spec */
    ;
    capi_spec_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "specpart.specpart.specpart.partition: failed to create array from the 1st argument `spec`";
    capi_spec_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,spec_Dims,spec_Rank,  capi_spec_intent,spec_capi,capi_errmess);
    if (capi_spec_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = specpart_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        spec = (float *)(PyArray_DATA(capi_spec_as_array));

    /* Processing variable nk */
    if (nk_capi == Py_None) nk = shape(spec, 0); else
        f2py_success = int_from_pyobj(&nk,nk_capi,"specpart.specpart.partition() 1st keyword (nk) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(spec, 0) == nk,"shape(spec, 0) == nk","1st keyword nk","partition:nk=%d",nk) {
    /* Processing variable nth */
    if (nth_capi == Py_None) nth = shape(spec, 1); else
        f2py_success = int_from_pyobj(&nth,nth_capi,"specpart.specpart.partition() 2nd keyword (nth) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(spec, 1) == nth,"shape(spec, 1) == nth","2nd keyword nth","partition:nth=%d",nth) {
    /* Processing variable ipart */
    ipart_Dims[0]=nk,ipart_Dims[1]=nth;
    capi_ipart_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char * capi_errmess = "specpart.specpart.specpart.partition: failed to create array from the hidden `ipart`";
    capi_ipart_as_array = ndarray_from_pyobj(  NPY_INT,1,ipart_Dims,ipart_Rank,  capi_ipart_intent,Py_None,capi_errmess);
    if (capi_ipart_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = specpart_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        ipart = (int *)(PyArray_DATA(capi_ipart_as_array));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(spec,ipart,&nk,&nth);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_ipart_as_array);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    }  /* if (capi_ipart_as_array == NULL) ... else of ipart */
    /* End of cleaning variable ipart */
    } /*CHECKSCALAR(shape(spec, 1) == nth)*/
    } /*if (f2py_success) of nth*/
    /* End of cleaning variable nth */
    } /*CHECKSCALAR(shape(spec, 0) == nk)*/
    } /*if (f2py_success) of nk*/
    /* End of cleaning variable nk */
    if((PyObject *)capi_spec_as_array!=spec_capi) {
        Py_XDECREF(capi_spec_as_array); }
    }  /* if (capi_spec_as_array == NULL) ... else of spec */
    /* End of cleaning variable spec */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/****************************** end of partition ******************************/

/*********************************** ptsort ***********************************/
static char doc_f2py_rout_specpart_specpart_ptsort[] = "\
ptsort(iihmax,nnspec)\n\nWrapper for ``ptsort``.\
\n\nParameters\n----------\n"
"iihmax : input int\n"
"nnspec : input int";
/*  */
static PyObject *f2py_rout_specpart_specpart_ptsort(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int iihmax = 0;
    PyObject *iihmax_capi = Py_None;
    int nnspec = 0;
    PyObject *nnspec_capi = Py_None;
    static char *capi_kwlist[] = {"iihmax","nnspec",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OO|:specpart.specpart.ptsort",\
        capi_kwlist,&iihmax_capi,&nnspec_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable iihmax */
        f2py_success = int_from_pyobj(&iihmax,iihmax_capi,"specpart.specpart.ptsort() 1st argument (iihmax) can't be converted to int");
    if (f2py_success) {
    /* Processing variable nnspec */
        f2py_success = int_from_pyobj(&nnspec,nnspec_capi,"specpart.specpart.ptsort() 2nd argument (nnspec) can't be converted to int");
    if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&iihmax,&nnspec);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*if (f2py_success) of nnspec*/
    /* End of cleaning variable nnspec */
    } /*if (f2py_success) of iihmax*/
    /* End of cleaning variable iihmax */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************* end of ptsort *******************************/

/*********************************** ptnghb ***********************************/
static char doc_f2py_rout_specpart_specpart_ptnghb[] = "\
ptnghb()\n\nWrapper for ``ptnghb``.\
\n";
/*  */
static PyObject *f2py_rout_specpart_specpart_ptnghb(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(void)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "|:specpart.specpart.ptnghb",\
        capi_kwlist))
        return NULL;
/*frompyobj*/
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)();
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************* end of ptnghb *******************************/

/*********************************** pt_fld ***********************************/
static char doc_f2py_rout_specpart_specpart_pt_fld[] = "\
npart = pt_fld(nnspec)\n\nWrapper for ``pt_fld``.\
\n\nParameters\n----------\n"
"nnspec : input int\n"
"\nReturns\n-------\n"
"npart : int";
/*  */
static PyObject *f2py_rout_specpart_specpart_pt_fld(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int nnspec = 0;
    PyObject *nnspec_capi = Py_None;
    int npart = 0;
    static char *capi_kwlist[] = {"nnspec",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:specpart.specpart.pt_fld",\
        capi_kwlist,&nnspec_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable nnspec */
        f2py_success = int_from_pyobj(&nnspec,nnspec_capi,"specpart.specpart.pt_fld() 1st argument (nnspec) can't be converted to int");
    if (f2py_success) {
    /* Processing variable npart */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&nnspec,&npart);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("i",npart);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable npart */
    } /*if (f2py_success) of nnspec*/
    /* End of cleaning variable nnspec */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************* end of pt_fld *******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/

static FortranDataDef f2py_specpart_def[] = {
  {"ihmax",0,{{-1}},NPY_INT, 1},
  {"npart",0,{{-1}},NPY_INT, 1},
  {"partinit",-1,{{-1}},0,0,NULL,(void *)f2py_rout_specpart_specpart_partinit,doc_f2py_rout_specpart_specpart_partinit},
  {"partition",-1,{{-1}},0,0,NULL,(void *)f2py_rout_specpart_specpart_partition,doc_f2py_rout_specpart_specpart_partition},
  {"ptsort",-1,{{-1}},0,0,NULL,(void *)f2py_rout_specpart_specpart_ptsort,doc_f2py_rout_specpart_specpart_ptsort},
  {"ptnghb",-1,{{-1}},0,0,NULL,(void *)f2py_rout_specpart_specpart_ptnghb,doc_f2py_rout_specpart_specpart_ptnghb},
  {"pt_fld",-1,{{-1}},0,0,NULL,(void *)f2py_rout_specpart_specpart_pt_fld,doc_f2py_rout_specpart_specpart_pt_fld},
  {NULL}
};

static void f2py_setup_specpart(char *ihmax,char *npart,char *partinit,char *partition,char *ptsort,char *ptnghb,char *pt_fld) {
  int i_f2py=0;
  f2py_specpart_def[i_f2py++].data = ihmax;
  f2py_specpart_def[i_f2py++].data = npart;
  f2py_specpart_def[i_f2py++].data = partinit;
  f2py_specpart_def[i_f2py++].data = partition;
  f2py_specpart_def[i_f2py++].data = ptsort;
  f2py_specpart_def[i_f2py++].data = ptnghb;
  f2py_specpart_def[i_f2py++].data = pt_fld;
}
extern void F_FUNC(f2pyinitspecpart,F2PYINITSPECPART)(void (*)(char*,char*,char *,char *,char *,char *,char *));
static void f2py_init_specpart(void) {
  F_FUNC(f2pyinitspecpart,F2PYINITSPECPART)(f2py_setup_specpart);
}

/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {

/*eof routine_defs*/
    {NULL}
};

static PyMethodDef f2py_module_methods[] = {

    {NULL,NULL}
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "specpart",
    NULL,
    -1,
    f2py_module_methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC PyInit_specpart(void) {
    int i;
    PyObject *m,*d, *s, *tmp;
    m = specpart_module = PyModule_Create(&moduledef);
    Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
    import_array();
    if (PyErr_Occurred())
        {PyErr_SetString(PyExc_ImportError, "can't initialize module specpart (failed to import numpy)"); return m;}
    d = PyModule_GetDict(m);
    s = PyUnicode_FromString("1.24.3");
    PyDict_SetItemString(d, "__version__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString(
        "This module 'specpart' is auto-generated with f2py (version:1.24.3).\nFunctions:\n"
"Fortran 90/95 modules:\n""  specpart --- ihmax,npart,partinit(),partition(),ptsort(),ptnghb(),pt_fld()"".");
    PyDict_SetItemString(d, "__doc__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString("1.24.3");
    PyDict_SetItemString(d, "__f2py_numpy_version__", s);
    Py_DECREF(s);
    specpart_error = PyErr_NewException ("specpart.error", NULL, NULL);
    /*
     * Store the error object inside the dict, so that it could get deallocated.
     * (in practice, this is a module, so it likely will not and cannot.)
     */
    PyDict_SetItemString(d, "_specpart_error", specpart_error);
    Py_DECREF(specpart_error);
    for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
        tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
        PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
        Py_DECREF(tmp);
    }





/*eof initf2pywraphooks*/
  PyDict_SetItemString(d, "specpart", PyFortranObject_New(f2py_specpart_def,f2py_init_specpart));
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
    if (! PyErr_Occurred())
        on_exit(f2py_report_on_exit,(void*)"specpart");
#endif
    return m;
}
#ifdef __cplusplus
}
#endif
